const Data = [
  {
    id: 1,
    tittle: "Waffle",
    desc: "Waffle with Berries",
    price: "6.50",
    img: "assets/images/image-waffle-desktop.jpg",
    imgT: "assets/images/image-waffle-thumbnail.jpg",
    imgP:"assets/images/image-waffle-mobile.jpg",
  },
  {
    id: 2,
    tittle: "Creme Brulee",
    desc: "Vanilla Bean Creme Brulee",
    price: "7.00",
    img: "assets/images/image-creme-brulee-desktop.jpg",
    imgT: "assets/images/image-creme-brulee-thumbnail.jpg",
    imgP:"assets/images/image-creme-brulee-mobile.jpg",
  },
  {
    id: 3,
    tittle: "Macaron",
    desc: "Macaron Mix of Five",
    price: "8.00",
    img: "assets/images/image-macaron-desktop.jpg",
    imgT: "assets/images/image-macaron-thumbnail.jpg",
    imgP:"assets/images/image-macaron-mobile.jpg",
  },
  {
    id: 4,
    tittle: "Tiramisu",
    desc: "Classic Tiramisu",
    price: "5.50",
    img: "assets/images/image-tiramisu-desktop.jpg",
    imgT: "assets/images/image-tiramisu-thumbnail.jpg",
    imgP:"assets/images/image-tiramisu-mobile.jpg",
  },
  {
    id: 5,
    tittle: "Baklava",
    desc: "Pistachio Baklava",
    price: "4.00",
    img: "assets/images/image-baklava-desktop.jpg",
    imgT: "assets/images/image-baklava-thumbnail.jpg",
    imgP:"assets/images/image-baklava-mobile.jpg",
  },
  {
    id: 6,
    tittle: "Pie",
    desc: "Lemon Maringue Pie",
    price: "5.00",
    img: "assets/images/image-meringue-desktop.jpg",
    imgT: "assets/images/image-meringue-thumbnail.jpg",
    imgP:"assets/images/image-meringue-mobile.jpg",
  },
  {
    id: 7,
    tittle: "Cake",
    desc: "red Velvet Cake",
    price: "4.50",
    img: "assets/images/image-cake-desktop.jpg",
    imgT: "assets/images/image-cake-thumbnail.jpg",
    imgP:"assets/images/image-cake-mobile.jpg",
  },
  {
    id: 8,
    tittle: "Brownie",
    desc: "salted Caramel Brownie",
    price: "5.50",
    img: "assets/images/image-brownie-desktop.jpg",
    imgT: "assets/images/image-brownie-thumbnail.jpg",
    imgP:"assets/images/image-brownie-mobile.jpg",
  },
  {
    id: 9,
    tittle: "Panna Cotta",
    desc: "Vanilla Panna Cotta",
    price: "6.50",
    img: "assets/images/image-panna-cotta-desktop.jpg",
    imgT: "assets/images/image-panna-cotta-thumbnail.jpg",
    imgP:"assets/images/image-panna-cotta-mobile.jpg",
  },
]

export default Data

